import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Html, Head, Main, NextScript } from 'next/document'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Neil MAHADALI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&family=Montserrat:wght@500&display=swap" rel="stylesheet"/>
      </head>
      <body className={inter.className}>{children}</body>
        
    </html>
  )
}
